"""Users password_hash added

Revision ID: 276dc54eb2c8
Revises: 85f48a977910
Create Date: 2025-09-20 19:28:21.686972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276dc54eb2c8'
down_revision = '85f48a977910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
